language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - more-stable

addons:
  sonarqube: true
env:
  global:
    - secure: "d6Ik5BuR0bozJe2VsTnkwSAjVB2rF2wB4vmaB/E9hix8b2gTczyUVL+dxXFJIKW9UM3bhIL5Zlunt+3zzyI2D0uHiDjM03gAgD6sWtLd1EZxHn/7W8592e+85COJPLSY29pt1H99rWsOeLyL2/GwmVcdYQpVm/wQQluzY2STpgDqSFaTcPt7yIGEzVedAChIqddkSkckoIrsj9JFkmRr/RkR5DiCpurPmvkmtheyVmzjHs3FSGPy5OXhj08OpqZjsRZcElHAYrxhb4hlxY4eNMmJ5aE4kYpgHygOunBEwSReeOi8jgX8YlBj/FwVHXbtF9E7fZAS1HEDtdGH48piHY4QyIiyG8erfiCSSI9SavuvTiM+NS7uIVEEI7p5XB+Zm/vfCLPDCzgGAiWE3RrBn0do4PiEKpRzUPQAB+gTDyr0Aq3N6cZXwW9OPg97TlYLEuNgvJn1j+qFQbyXuTmmImqUhhjoYB06wgX2hOyXoaGmmkZSPio/L6MTZ3IB3Qn2nGt/O6oSV5heg4zHTcmFWVpOQwCtsGaIyrVbIe+SpHohWCTbLWqO2PBNLZldusfqTOyuW2u+wCz4ATcfRjPGo56GAFIHSmUdtmTIujtbsNyr6mFXAJ3o/IOUrAuRYkj6J6G/vnA7qgHZ1BBjDwwCYiGmooj/vb18Zx4D8fI8bh8="
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
