package il.org.spartan.Leonidas.plugin.GUI.TipperCreator;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

/**
 * @author Anna Belozovsky
 * @since 12/05/2017
 */
public class TipperNameCreator extends JFrame {
    private JButton saveButton;
    private JButton cancelButton;
    private JPanel mainPanel;
    private JTextField nameField;
    private TipperCreator callee;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    TipperNameCreator(TipperCreator callee) {
        super("Name new tipper");
        this.callee = callee;
        setContentPane(mainPanel);
        setPreferredSize(new Dimension(300, 100));
        setResizable(false);
        pack();
        setVisible(true);
        saveButton.addActionListener(e -> saveButtonClicked());
        cancelButton.addActionListener(e -> cancelButtonClicked());
    }

    private void saveButtonClicked() {
        String name = nameField.getText();
        if (name.matches("[a-zA-Z][a-zA-Z0-9]*")) {
            if (getClass().getClassLoader().getResource("il/org/spartan/Leonidas/plugin/tippers/leonidas/" + name + ".java") != null) {
                JOptionPane.showMessageDialog(this, "A tipper with that name already exists.");
                return;
            }
            callee.tipperName = name;
            dispose();
        } else if (name.matches("[0-9][a-zA-Z0-9]*")) {
            JOptionPane.showMessageDialog(this, "A name cannot start with a number.");
        } else if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Name cannot be empty");
        } else {
            JOptionPane.showMessageDialog(this, "Only letters and numbers are allowed.");
        }
    }

    private void cancelButtonClicked() {
        dispose();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        nameField = new JTextField();
        nameField.setText("");
        mainPanel.add(nameField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Insert name:");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        saveButton = new JButton();
        saveButton.setText("Save");
        panel1.add(saveButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        panel1.add(cancelButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
