package il.org.spartan.Leonidas.plugin.GUI.ToolBoxController;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import il.org.spartan.Leonidas.plugin.leonidas.LeonidasUtils;
import il.org.spartan.Leonidas.plugin.tippers.leonidas.LeonidasTipperDefinition;
import org.reflections.Reflections;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.lang.annotation.Annotation;
import java.lang.reflect.Method;

/**
 * @author Amir Sagiv, Anna Belozovsky
 * @since 14-05-2017
 */
public class EditTipper extends JFrame {
    private JPanel mainPanel;
    private JButton button1;
    private JButton button2;
    private JPanel tempPane;
    private JScrollPane TablePanel;
    private LeonidasUtils tipperAnnotation;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public EditTipper(String tipperName) {
        super("Edit Tipper");
        (new Reflections(LeonidasTipperDefinition.class)).getSubTypesOf(LeonidasTipperDefinition.class)
                .forEach(c -> {
//                    JOptionPane.showMessageDialog(this, c.getSimpleName() + ", " + tipperName);
                    if (c.getSimpleName().equals(tipperName)) {
                        Annotation[] annotations = c.getAnnotations();
                        for (Annotation annotation : annotations) {

//                            System.err.println(annotation.annotationType().getSimpleName());
                            if (annotation.annotationType().getSimpleName().equals("LeonidasUtils")) {
                                tipperAnnotation = (LeonidasUtils) annotation;
                            }
                        }
                    }
                });

        int i = 0;
        ComponentJTable table = new ComponentJTable();
        Method[] methods = tipperAnnotation.getClass().getDeclaredMethods();
        ((DefaultTableModel) table.getModel()).setRowCount(methods.length);
        for (Method method : methods) {
            if (method.getName().equals("toString")) {
                continue;
            }
            Class returnType = method.getReturnType();
            try {
                if (returnType.isPrimitive() && returnType.getName().equals("boolean")) {
                    table.getModel().setValueAt(new JLabel(method.getName()), i, 0);
                    table.getModel().setValueAt(new JCheckBox("", (Boolean) method.invoke(tipperAnnotation)), i++, 1);
                    continue;
                }
                Object obj = returnType.newInstance();
                if (obj instanceof String) {

                    table.getModel().setValueAt(new JLabel(method.getName()), i, 0);
                    table.getModel().setValueAt(new JTextField((String) method.invoke(tipperAnnotation)), i++, 1);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        //model.setRowCount(4);
        //model.setColumnCount(2);

        //((DefaultTableModel)table.getModel()).addRow();

//        table.getModel().setValueAt(new JLabel("CheckBox"), 0, 0);
//        table.getModel().setValueAt(new JCheckBox(), 0, 1);
//        table.getModel().setValueAt(new JLabel("Text"), 1, 0);
//        table.getModel().setValueAt(new JTextField(), 1, 1);
        //JList<String> table = new JList<>();
        TablePanel.setViewportView(table);
        setContentPane(mainPanel);
        setPreferredSize(new Dimension(800, 600));
        setResizable(false);
        pack();
        setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 28));
        label1.setText("Label");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tempPane = new JPanel();
        tempPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(tempPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        TablePanel = new JScrollPane();
        tempPane.add(TablePanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button2 = new JButton();
        button2.setText("Button");
        panel1.add(button2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
